<a href="https://colab.research.google.com/github/aryana64/NIPT/blob/main/biocad_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#import pickle
#import numpy as np
#import pickle
#import numpy as np
#import os
#import sklearn
#from sklearn.model_selection import train_test_split
#import tensorflow as tf
import pandas as pd

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
!unzip "/content/drive/MyDrive/Colab Notebooks/monitoringanaliz.zip" -d "/content/drive/MyDrive/Colab Notebooks/biocad"

Archive:  /content/drive/MyDrive/Colab Notebooks/monitoringanaliz.zip
   creating: /content/drive/MyDrive/Colab Notebooks/biocad/monitoringanaliz/
  inflating: /content/drive/MyDrive/Colab Notebooks/biocad/monitoringanaliz/X_test.csv
  inflating: /content/drive/MyDrive/Colab Notebooks/biocad/monitoringanaliz/X_train.csv
  inflating: /content/drive/MyDrive/Colab Notebooks/biocad/monitoringanaliz/Y_train.csv
  inflating: /content/drive/MyDrive/Colab Notebooks/biocad/monitoringanaliz/Задание.docx

In [7]:
x_text=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/biocad/monitoringanaliz/X_test.csv')
x_train=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/biocad/monitoringanaliz/X_train.csv')
y_train=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/biocad/monitoringanaliz/Y_train.csv')

In [8]:
x_train.head()

,Time (h),Aeration rate(Fg:L/h),Agitator RPM(RPM:RPM),Sugar feed rate(Fs:L/h),Acid flow rate(Fa:L/h),Base flow rate(Fb:L/h),Heating/cooling water flow rate(Fc:L/h),Heating water flow rate(Fh:L/h),Water for injection/dilution(Fw:L/h),Air head pressure(pressure:bar),...,Oxygen in percent in off-gas(O2:O2 (%)),Offline Penicillin concentration(P_offline:P(g L^{-1})),Offline Biomass concentratio(X_offline:X(g L^{-1})),Carbon evolution rate(CER:g/h),Ammonia shots(NH3_shots:kgs),Viscosity(Viscosity_offline:centPoise),Fault reference(Fault_ref:Fault ref),1- No Raman spec,1-Raman spec recorded,2-PAT control(PAT_ref:PAT ref)
0,0.2,30,100,8,0.0000,30.118,9.8335,0.0001,0,0.6,...,0.19595,NaN,NaN,0.034045,0,NaN,0,1,1,1
1,0.4,30,100,8,0.0000,51.221,18.1550,0.0001,0,0.6,...,0.20390,NaN,NaN,0.038702,0,NaN,0,1,1,1
2,0.6,30,100,8,0.0000,54.302,9.5982,0.0001,0,0.6,...,0.20575,NaN,NaN,0.040240,0,NaN,0,1,1,1
3,0.8,30,100,8,0.0000,37.816,4.3395,0.0001,0,0.6,...,0.20602,NaN,NaN,0.041149,0,NaN,0,1,1,1
4,1.0,30,100,8,0.5181,18.908,1.1045,0.0001,0,0.6,...,0.20589,1.017800e-25,0.52808,0.041951,0,4.083,0,1,1,1

In [9]:
y_train.head()

   pH(pH:pH)
0     6.4472
1     6.4932
2     6.5425
3     6.5753
4     6.5825